### ISSUE TITLE
oEmbed service discovery for non-HTML docs?

### ISSUE THREAD

**Issue by joeapearson** [iamcal/oembed#269]
With reference to https://oembed.com/ section 4 (Service Discovery), it seems that the recommended means of allowing clients to discover an oEmbed service is via some `<link>` tags in a document body.

Is there a standardised or recommended means for clients to discover oEmbed services for non-HTML data, and/or without having to download and parse the HTML itself?  For example, an HTTP header served with the document, something like this:

`OEmbed-Provider: https://reference/to/my/oembed/service?url=http://url/to/my/document`

... or some other mechanism?

**Comment by merih** [comment]
Actually [Link header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) is the equiavalent for `<link>` element, and while implementing oembed spec, I thought it would also be accepted but I guess since it's not specifically written as such, when I tested the consumers didn't take this into account.
