### ISSUE TITLE
no cookies video

### ISSUE THREAD

**Issue by micker** [iamcal/oembed#729]
is it possible to embed video without cookie for youtube, vimeo ?
regards

**Comment by iamcal** [comment]
That is up to each individual provider - oEmbed is just the discovery mechanism

**Comment by micker** [comment]
Ok thanks

**Comment by CanRau** [comment]
@micker Not sure that helps though for cookie compliance reasons (GDPR etc) one common option is to only show a static thumbnail image with a play button and a notice that clicking it makes you agree to the 3rd party's privacy policy possibly saving that for later so that the user only had to agree once, there's ready made libraries, components and plugins for that
